### PR TITLE
feat(txtmap): Add support for a linebased mindmap file

### PR DESCRIPTION
**Pull request by EdJoPaTo**
The txtmap file structure is based on my own thoughts because i did not found a
format for mindmaps (or tree views) with a simple line based structure.

### CODE REVIEW

**Comment by dundalek** [comment]
Thanks, looks good.

**Comment by EdJoPaTo** [comment]
@dundalek can you add it to the atom package as well?
I took a look at the sources but I'm not that familiar with atom packages and not quite sure what have to be done in order to get it working to 'understand' that kind of file.
(Just a general question, not a 'do it now')

**Comment by dundalek** [comment]
The way to do it is to add the new parse function [here](https://github.com/dundalek/atom-markdown-mindmap/blob/master/lib/markdown-mindmap-view.coffee#L220). However, I am not yet sure how to detect when to use the original markdown parser and when to use your function. Maybe we try markdown first and when it fails to parse or is empty we try to fallback to the plain text version?

**Comment by EdJoPaTo** [comment]
It should be done in a future proof way with more parsers supported. Maybe from a file extension/ the detected file content (markdown, plaintext, ...)?

**Comment by dundalek** [comment]
Yeah, that sounds like it could work. I think I'll take a stab at it probably sometime next week.

**Pull request merged**
